version: "3"

services:
  api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ../api

    ports:
      - "8000:8000"

  website:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ../website

    ports:
      - "8080:3000"
